dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "amfyWebService"

script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner