dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "amfyWebService"
    token:
      secure: $SONAR_TOKEN

script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner